

BASENAME=Modelo-Dissert-DCOMP
TEXNAME=$(BASENAME).tex

all:
	pdflatex --shell-escape $(TEXNAME)


clean:
	rm -f $(BASENAME).aux
	rm -f $(BASENAME).idx
	rm -f $(BASENAME).lof
	rm -f $(BASENAME).log
	rm -f $(BASENAME).lol
	rm -f $(BASENAME).lot
	rm -f $(BASENAME).toc





